### ISSUE TITLE
如何对4CH小板调参

### ISSUE THREAD

**Issue by ghost** [AnalogDragon/Taiko-Input#1]
需要用底下的测试点，还是按什么按键通过ch552转出串口通过usb对板载stm32调参？

另：感谢开源!!!世界顶级太鼓IO板（（（（
很好太极鼓黑板，爱来自瓷器

**Comment by ghost** [comment]
寄了，才看见原来主页里面写了“需要通过测试点调参”，我是傻*

**Comment by AnalogDragon** [comment]
其实默认参数应该一般鼓够用【
